### PR TITLE
chore: improve `package.json`

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Improve `package.json`.
  - Add issue tracker/homepage URL.
  - Add `lib` and `tests` directories.

### CODE REVIEW

**Comment by jiro4989** [comment]
Please don't change indent size.

**Comment by Panquesito7** [comment]
> It's difficult to review if all lines are diffs, so please only make necessary changes.

Weird. I copied the original `package.json` and just added other fields such as the Git repository and issue tracker links by using `npm init`. 🤔

**Comment by jiro4989** [comment]
The newline character has been changed from CRLF to LF.

```bash
~/src/github.com
⟩ od -c jiro4989/setup-nim-action/package.json | head -n 5
0000000   {  \r  \n           "   n   a   m   e   "   :       "   s   e
0000020   t   u   p   -   n   i   m   "   ,  \r  \n           "   v   e
0000040   r   s   i   o   n   "   :       "   1   .   0   .   0   "   ,
0000060  \r  \n           "   p   r   i   v   a   t   e   "   :       t
0000100   r   u   e   ,  \r  \n           "   d   e   s   c   r   i   p

~/src/github.com
⟩ od -c Panquesito7/setup-nim-action/package.json | head -n 5
0000000   {  \n           "   n   a   m   e   "   :       "   s   e   t
0000020   u   p   -   n   i   m   "   ,  \n           "   v   e   r   s
0000040   i   o   n   "   :       "   1   .   0   .   0   "   ,  \n
0000060       "   p   r   i   v   a   t   e   "   :       t   r   u   e
0000100   ,  \n           "   d   e   s   c   r   i   p   t   i   o   n
```

**Comment by Panquesito7** [comment]
Uh, well, I'm still not 100% sure how that can be fixed. Sorry for my ignorance. 😅

**Comment by jiro4989** [comment]
If you don't know what a newline character is, look it up yourself

**Comment by Panquesito7** [comment]
These are the changes I made.

image

**Comment by jiro4989** [comment]
My diff

image

**Comment by jiro4989** [comment]
Your PR description doesn't mention the newline character.
However, the newline character has been changed in PR.

Since there is no description about the newline character, it seems to me that "I do not know the newline character, but I am making changes".
If the newline character change is intended, it should be write the description of the PR.
And if not, it should not be changed.

Otherwise, I wouldn't merge your changes because they are "irresponsible changes, or changes without understanding".

**Comment by Panquesito7** [comment]
1. I did not intend the change of the endline. I tried to fix it, but same results.
2. I copied the original `package.json` and made the necessary changes and nothing else (like in the image I showed). But the Git diff still shows something different.

If you want, you can try implementing these changes yourself if you don't feel safe about it.

**Comment by jiro4989** [comment]
Hmm, well, the unit test passed, so it should be fine

**Comment by jiro4989** [comment]
LGTM👍

LGTM

**Comment by Panquesito7** [comment]
Thanks, and sorry for the inconveniencies. 🙂

**Pull request merged**
